import { Button, Card, CardActions, CardContent, CardMedia, Typography } from '@material-ui/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Product, products } from '../model'
import styles from '../../styles/Home.module.css'


const ProductListPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listagem de Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography component="h1" variant = "h3" color ="textPrimary" gutterBottom>
        Produtos
      </Typography>
      {
        products.map((product , key) => (
          <Card key={key}>
            <CardMedia style={{paddingTop:"56%"}} image={product.image_url}/>
            <CardContent>
              <Typography component="h2" variant='h5' gutterBottom>
                {product.name}
              </Typography>
            </CardContent>
            <CardActions>
              <Button size='small' color="primary" component="a">Detalhes</Button>
            </CardActions>
          </Card>
        ))
      }
    </div>
  )
}

export default ProductListPage
